apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-worker
          ports:
            - containerPort: 3000